/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_WATCHDOG_GENERATED_TRACERS_H
#define TRACE_HW_WATCHDOG_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_CMSDK_APB_WATCHDOG_READ_EVENT;
extern TraceEvent _TRACE_CMSDK_APB_WATCHDOG_WRITE_EVENT;
extern TraceEvent _TRACE_CMSDK_APB_WATCHDOG_RESET_EVENT;
extern uint16_t _TRACE_CMSDK_APB_WATCHDOG_READ_DSTATE;
extern uint16_t _TRACE_CMSDK_APB_WATCHDOG_WRITE_DSTATE;
extern uint16_t _TRACE_CMSDK_APB_WATCHDOG_RESET_DSTATE;
#define TRACE_CMSDK_APB_WATCHDOG_READ_ENABLED 1
#define TRACE_CMSDK_APB_WATCHDOG_WRITE_ENABLED 1
#define TRACE_CMSDK_APB_WATCHDOG_RESET_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_CMSDK_APB_WATCHDOG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CMSDK_APB_WATCHDOG_READ) || \
    false)

static inline void _nocheck__trace_cmsdk_apb_watchdog_read(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_CMSDK_APB_WATCHDOG_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:cmsdk_apb_watchdog_read " "CMSDK APB watchdog read: offset 0x%" PRIx64 " data 0x%" PRIx64 " size %u" "\n",
                 qemu_get_thread_id(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 , offset, data, size);
    }
}

static inline void trace_cmsdk_apb_watchdog_read(uint64_t offset, uint64_t data, unsigned size)
{
    if (true) {
        _nocheck__trace_cmsdk_apb_watchdog_read(offset, data, size);
    }
}

#define TRACE_CMSDK_APB_WATCHDOG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CMSDK_APB_WATCHDOG_WRITE) || \
    false)

static inline void _nocheck__trace_cmsdk_apb_watchdog_write(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_CMSDK_APB_WATCHDOG_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:cmsdk_apb_watchdog_write " "CMSDK APB watchdog write: offset 0x%" PRIx64 " data 0x%" PRIx64 " size %u" "\n",
                 qemu_get_thread_id(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 , offset, data, size);
    }
}

static inline void trace_cmsdk_apb_watchdog_write(uint64_t offset, uint64_t data, unsigned size)
{
    if (true) {
        _nocheck__trace_cmsdk_apb_watchdog_write(offset, data, size);
    }
}

#define TRACE_CMSDK_APB_WATCHDOG_RESET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CMSDK_APB_WATCHDOG_RESET) || \
    false)

static inline void _nocheck__trace_cmsdk_apb_watchdog_reset(void)
{
    if (trace_event_get_state(TRACE_CMSDK_APB_WATCHDOG_RESET) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:cmsdk_apb_watchdog_reset " "CMSDK APB watchdog: reset" "\n",
                 qemu_get_thread_id(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 );
    }
}

static inline void trace_cmsdk_apb_watchdog_reset(void)
{
    if (true) {
        _nocheck__trace_cmsdk_apb_watchdog_reset();
    }
}
#endif /* TRACE_HW_WATCHDOG_GENERATED_TRACERS_H */
